#!/usr/bin/env bash

AUR=$(yay -Qua | wc -l)
OFFICIAL=$(checkupdates | wc -l)

case $1 in
    aur) echo "$AUR";;
    official) echo "$OFFICIAL";;
    update)
        kitty --title update-sys sh -c 'yay -Syu --noconfirm --answerdiff N --answerclean N'
        ;;
    "")
        COUNT=$((OFFICIAL+AUR))
        [[ "$COUNT" -eq 0 ]] && echo "" || echo "$COUNT"
        ;;
esac
