#!/usr/bin/env bash

# Calculate updates for each service
AUR=$(yay -Qua | wc -l)
OFFICIAL=$(checkupdates | wc -l)

# Case/switch for each service updates
case $1 in
    aur) echo "$AUR";;
    official) echo "$OFFICIAL";;
esac

# If the parameter is "update", update all services
if [ "$1" = "update" ]; then
    kitty --title update-sys sh -c 'yay -Syu --answerdiff N --answerclean N'
fi

# If there aren't any parameters, return the total number of updates
if [ "$1" = "" ]; then
    COUNT=$((OFFICIAL+AUR))

    if [[ "$COUNT" = "0" ]]
    then
        echo ""
    else
        echo "$COUNT"
    fi
    exit 0
fi
